import Link from "next/link";
import type { ReactNode } from "react";
import { AlertTriangle, Info, ShieldAlert, CheckCircle2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

// Semantic palette — status is never conveyed by color alone (icon + text too).
export type Severity = "critical" | "warning" | "info" | "success" | "neutral";

export const SEVERITY_META: Record<Severity, { color: string; ring: string; icon: typeof Info; label: string }> = {
  critical: { color: "text-destructive dark:text-red-400", ring: "border-destructive/40 bg-destructive/10", icon: ShieldAlert, label: "Critical" },
  warning: { color: "text-amber-600 dark:text-amber-400", ring: "border-amber-500/40 bg-amber-500/10", icon: AlertTriangle, label: "Warning" },
  info: { color: "text-blue-600 dark:text-blue-400", ring: "border-blue-500/40 bg-blue-500/10", icon: Info, label: "Information" },
  success: { color: "text-emerald-600 dark:text-emerald-400", ring: "border-emerald-500/40 bg-emerald-500/10", icon: CheckCircle2, label: "OK" },
  neutral: { color: "text-muted-foreground", ring: "border-border bg-muted/30", icon: Info, label: "Info" },
};

/** A titled card that wraps a chart or table section. */
export function ChartCard({ title, action, children, className }: { title: string; action?: ReactNode; children: ReactNode; className?: string }) {
  return (
    <Card className={className}>
      <CardHeader className="flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm">{title}</CardTitle>
        {action}
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}

/** Standard on-screen report header (company / report / period / generated by). */
export function ReportHeader({
  reportName, period, generatedBy, generatedAt,
}: {
  reportName: string; period?: string; generatedBy?: string; generatedAt?: Date;
}) {
  const when = (generatedAt ?? new Date()).toLocaleString("th-TH", { timeZone: "Asia/Bangkok", dateStyle: "medium", timeStyle: "short" });
  return (
    <div className="mb-4 rounded-lg border bg-card p-4">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Chaithanin Co.,Ltd.</p>
          <h2 className="text-lg font-bold">{reportName}</h2>
        </div>
        <dl className="text-right text-xs text-muted-foreground">
          {period && <div>ช่วงข้อมูล / Period: <span className="font-medium text-foreground">{period}</span></div>}
          <div>สร้างเมื่อ / Generated: <span className="font-medium text-foreground">{when}</span></div>
          {generatedBy && <div>โดย / By: <span className="font-medium text-foreground">{generatedBy}</span></div>}
        </dl>
      </div>
    </div>
  );
}

/** Auto-generated executive summary paragraph (text is built from real data). */
export function ExecutiveSummary({ children }: { children: ReactNode }) {
  return (
    <div className="mb-4 rounded-lg border border-blue-500/30 bg-blue-500/5 p-4">
      <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-blue-700 dark:text-blue-300">
        บทสรุปผู้บริหาร / Executive Summary
      </p>
      <p className="text-sm leading-relaxed text-foreground">{children}</p>
    </div>
  );
}

export interface AlertEntry {
  severity: Severity;
  title: string;
  detail?: string;
  href?: string;
  count?: number;
}

/** Central alert list — each row links to the related detail when href is set. */
export function AlertList({ alerts, emptyText = "ไม่มีการแจ้งเตือน / No alerts" }: { alerts: AlertEntry[]; emptyText?: string }) {
  if (alerts.length === 0) {
    return <p className="flex items-center gap-2 text-sm text-emerald-600 dark:text-emerald-400"><CheckCircle2 className="h-4 w-4" /> {emptyText}</p>;
  }
  return (
    <ul className="space-y-2">
      {alerts.map((a, i) => {
        const meta = SEVERITY_META[a.severity];
        const Icon = meta.icon;
        const body = (
          <div className={cn("flex items-start gap-3 rounded-md border p-3 text-sm", meta.ring, a.href && "transition-shadow hover:shadow-sm")}>
            <Icon className={cn("mt-0.5 h-4 w-4 shrink-0", meta.color)} />
            <div className="min-w-0 flex-1">
              <p className="font-medium">{a.title}{a.count != null && <span className={cn("ml-1 font-bold tabular-nums", meta.color)}>({a.count})</span>}</p>
              {a.detail && <p className="text-xs text-muted-foreground">{a.detail}</p>}
            </div>
          </div>
        );
        return <li key={i}>{a.href ? <Link href={a.href}>{body}</Link> : body}</li>;
      })}
    </ul>
  );
}
